backend:
  name: github
  repo: oleksandr-storchak/site
  branch: main
  auth_type: github
  app_id: Ov23lipRjwvuvUIvRauC

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "index"
        file: "index.markdown"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - label: "About"
        name: "about"
        file: "about.markdown"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Layout", name: "layout", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
